### ISSUE TITLE
Compilation errors due to your usage of lombok

### ISSUE THREAD

**Issue by ryancrawcour** [Azure/azure-documentdb-changefeedprocessor-java#23]
the readme file of the project says eclipse can be used for this project. However when I import the project in eclipse I get a lot of compilation errors due to your usage of lombok. Please consider fixing this. For a user to evaluate a library one of the criteria is the project should be importable to eclipse. I am guessing there has to be some eclipse configuration or eclipse plugin needed. Please add the configuration to maven pom file or if needed explain in the readme how the additional plugin for lombok should be installed.

**Comment by romitgirdhar** [comment]
This was solved by PR #40
